CREATE TABLE [dbo].[Tamagochis]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] VARCHAR(255) NOT NULL,
	[Age] INT NOT NULL,
	[Currency] DECIMAL(11,2) NULL,
	[Level] INT NOT NULL DEFAULT 0,
	[Health] INT NOT NULL DEFAULT 100,
	[Hapinness] TINYINT NOT NULL DEFAULT 0,
	[Alive] TINYINT NOT NULL DEFAULT 1
)
